//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanInstruments.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int CalibrationId { get; set; }
        public int DeviceId { get; set; }
        public double LowFreq { get; set; }
        public double HighFreq { get; set; }
        public double Tone { get; set; }
        public double RefLevel { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
