//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OceanInstruments.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int ModelId { get; set; }
        public string Code { get; set; }
        public string FullDesc { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
    }
}
